Тема 1, здание 1 

In [10]:
import numpy as np

In [3]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

print(a)

print("Размерность a: {}".format(a.ndim))

print("Форма a: {}".format(a.shape))

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Размерность a: 2
Форма a: (5, 2)


In [6]:
a_mean(axis = 0)

array([2. , 8.4])

Задание 2

In [7]:
a_centered = np.array([[-1, -2.4],
                       [ 0, -0.4],
                       [ 1,  2.6],
                       [ 1,  1.6],
                       [-1, -1.4]])
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [8]:
column_1 = np.array([-1, 0, 1, 1, -1])
column_2 = np.array([-2.4, -0.4, 2.6, 1.6, -1.4])
a_centered = ([column_1, column_2])
a_centered_sp = np.dot(column_1, column_2)
a_centered_sp

8.0

In [ ]:
N = 52, N-1 = 51
a_centered_sp / (N - 1) = 8/51

Задание 4

In [ ]:
ну не смог я, просто уже не успеваю

Тема 2, задание 1

In [10]:
import pandas as pd
import numpy as np

In [12]:
authors = {
    "author_id": [1, 2, 3],
    "author_name": ["Тургенев", "Чехов", "Островский"]
}

b = pd.DataFrame(authors)

b

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [8]:
book = {
    "auhtor_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ["Отцы и дети", "Рудин", "Дворянское гнездо", "Толстый и тонкий", "Дама с собачкой", "Гроза", 
                    "Таланты и поклонники"],
    "price": [400, 300, 350, 500, 450, 370, 290]
}

b = pd.DataFrame(book)

b

auhtor_id            book_title  price
0          1           Отцы и дети    400
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

In [14]:
author_price = pd.merge(authors, book, on='author_id', how='outer')
author_price

TypeError: Can only merge Series or DataFrame objects, a <class 'dict'> was passed

In [ ]:
и дальше этой ошибки не могу пройти, прошу помочь и разобрать ДЗ